from fastapi import APIRouter, HTTPException, Depends, status, Response
from fastapi.responses import JSONResponse
from models.types import UserCreate, UserLogin, Token, User
from core.database import db
from core.auth import create_access_token, get_current_active_user
from datetime import timedelta, datetime
import logging

logger = logging.getLogger(__name__)

router = APIRouter()

@router.post("/register")
async def register_user(user_data: UserCreate, response: Response):
    """Register a new user and log them in by setting a cookie."""
    existing_user = db.get_user_by_email(user_data.email)
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email already registered"
        )
    
    user = db.create_user(user_data)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to create user"
        )
    
    access_token = create_access_token(
        data={"sub": user.email}
    )
    
    logger.info(f"New user registered and logged in: {user.email}")
    
    response.set_cookie(
        key="access_token",
        value=access_token,
        httponly=True,
        samesite="lax",
        secure=False # Set to True in production with HTTPS
    )
    
    return {"message": "Registration successful", "user": user.dict()}


@router.post("/login")
async def login_user(user_data: UserLogin, response: Response):
    """Login user and set access_token cookie"""
    user = db.authenticate_user(user_data.email, user_data.password)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    access_token = create_access_token(
        data={"sub": user.email}
    )
    
    logger.info(f"User logged in: {user.email}")
    
    response.set_cookie(
        key="access_token",
        value=access_token,
        httponly=True,
        samesite="lax",
        secure=False # Set to True in production with HTTPS
    )
    
    return {"message": "Login successful", "user": user.dict()}

@router.post("/logout")
async def logout(response: Response):
    """Logs out the user by clearing the access token cookie."""
    logger.info("User logging out.")
    response.delete_cookie("access_token")
    return {"message": "Successfully logged out"}

@router.get("/me", response_model=User)
async def get_current_user_info(current_user: User = Depends(get_current_active_user)):
    """Get current user information"""
    if not current_user:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Not authenticated")
    return current_user

@router.get("/my-pdfs")
async def get_user_pdfs(current_user: User = Depends(get_current_active_user)):
    """Get all PDFs generated by the current user"""
    if not current_user:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Not authenticated")
    user_pdfs = db.get_user_pdfs(current_user.id)
    return JSONResponse(content={"pdfs": user_pdfs}) 